name: .NET

on: push

jobs:
  publish:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --nologo --no-restore --configuration Release
      - name: Publish
        run: dotnet publish --nologo --no-build --configuration Release --output publish
      - name: Zip
        run: Compress-Archive -Path publish/* -DestinationPath AssemblyInformation.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssemblyInformation.zip
          path: publish/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: AssemblyInformation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}